config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'sessions#home'

  get '/signup' => 'users#new'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  get '/auth/facebook/callback' => 'sessions#fbcreate'


  resources :users
  resources :meal_plans
  resources :meals, only: [:edit, :index, :show ]
  resources :meal_schedules

  resources :meal_plans do
    resources :meal_schedules, only: [:new, :index, :create]
  end

  resources :meals do
    resources :meal_schedules, only: [:new, :index, :create]
  end

  resources :meal_plans do
  resources :likes, only: [:create]
  member do
    post 'like'
  end
end
end

app/models/meal_plan.rb
class MealPlan < ApplicationRecord
  belongs_to :user
  has_many :meal_schedules, dependent: :destroy
  has_many :meals, through: :meal_schedules, dependent: :destroy

  validates :goal, :description, presence: true
  default_scope -> { order(updated_at: :desc)}

end

app/controllers/meal_plans_controller.rb
class MealPlansController < ApplicationController
  before_action :set_meal_plan, only: [:edit, :update, :show, :delete]
  before_action :redirect_if_not_logged_in, only: [:new, :create, :edit, :update]
  before_action :require_same_user, only: [:edit, :update, :delete]

  def index
    @meal_plans = current_user.meal_plans.paginate(page: params[:page], per_page: 2)
  end

  def show
  end

  def new
    @meal_plan = MealPlan.new
    @meal_plan.meal_schedules.build
    @meal = Meal.new
  end

  def create
    @meal_plan = current_user.meal_plans.build(meal_plan_params)

    if @meal_plan.save
      flash[:success] = "Your meal plan was created!"
      ms = MealSchedule.new(meal_schedule_params)
      ms.meal_plan = @meal_plan
      ms.save
      redirect_to meal_plan_path(@meal_plan)
    else
      render :new
    end
  end


  def edit
  end

  def update
    if @meal_plan.update(meal_plan_params)
      flash[:success] = "Your changes were saved!"
      redirect_to meal_plan_path(@meal_plan)
    else
      render :edit
    end
  end

  def destroy
    @meal_plan.destroy
    flash[:success] = "Your meal plan and all associated meals were deleted!"
    redirect_to meal_plans_path
  end

private

  def meal_plan_params
    params.require(:meal_plan).permit(:goal, :description)
  end

  def meal_schedule_params
    params.require(:meal_plan).require(:meal_schedule).permit(:eating_time, :meal_type, :meal_id,
      meal: [:protein, :vegetable, :side, :beverage, :beverage_ounces, :favorite, :day])
  end

  def set_meal_plan
    @meal_plan = MealPlan.find(params[:id])
    if @meal_plan.nil?
      flash[:danger] = "Meal Plan not Found!"
      redirect_to meal_plans_path
    end
  end

  def require_same_user
    if current_user.id != @meal_plan.user_id
      flash[:danger] = "You can only edit or delete your own meal plan"
      redirect_to meal_plans_path
    end
  end
end

app/helpers/meal_plans_helper.rb
module MealPlansHelper
end

app/views/meal_plans/_form.html.erb
<div class="col-md-8 well">
  <%= form_for (@meal_plan)  do |f| %>
    <%= render partial: 'layouts/errors', locals: {object: @meal_plan} %>
    <h4><center>Create a meal plan:</h4></center>

  <div class="center">
    <%= f.label :goal %>
    <%= f.select(:goal, ["Weight Loss", "Tone", "Fat Loss", "Gain Muscle", "Maintain"]) %>
  </div>

  <div class="center">
    <%= f.label :description %>
    <%= f.select(:description, ["Regular", "Vegetarian", "Vegan", "Pescatarian", "Gluten Free", "Keto"]) %>
  </div>
  <br><br>
</div>


    <div class="col-md-8 well">
      <h4><center>Add your meal schedule:</h4></center>
      <%= f.fields_for :meal_schedule do |ms|%>

    <div class="center">
      <%= ms.label :eating_time %>
      <%= ms.select(:eating_time, ["Morning", "Afternoon", "Evening", "Night"]) %>
    </div>

    <div class="center">
      <%= ms.label :meal_type %>
      <%= ms.select(:meal_type, ["Breakfast", "Lunch", "Dinner", "Snack", "Dessert"]) %>
    </div>
  </div>

      <div class="col-md-8 well">
        <h4><center>Add your meal:</h4></center>
        <%= ms.fields_for :meal do |m|%>
          <%= m.label :protein %>
          <%= m.text_field :protein, placeholder: "Chicken", required: true %>

          <%= m.label :vegetable %>
          <%= m.text_field :vegetable, placeholder: "Spinach", required: true  %>

          <%= m.label :side %>
          <%= m.text_field :side, placeholder: "Fries", required: true  %>

          <%= m.label :beverage %>
          <%= m.text_field :beverage, placeholder: "Water", required: true  %>

          <%= m.label :beverage_ounces %>
          <%= m.number_field :beverage_ounces, placeholder: "16 ounces", required: true  %>

          <%= m.label :day %>
          <%= m.date_field :day, required: true  %>

          <%= m.label :favorite %>
          <%= m.select :favorite, [['No', 'false'],['Yes', 'true']], required: true  %>

          <% end %>
      <% end %>

<div class="center">
  <%= f.submit %>
</div>
<% end %>

app/views/meal_plans/_mealplan.html.erb
<% obj.each do |mealplan| %>
  <div class="row">
    <div class="col-md-2">
      <section class ="center">

      </section>
    </div>
    <% if mealplan.meals.favorite.count != 0 %>

      <div>
        <h4>Your Favorite Foods: </h4>
          <% mealplan.meals.favorite.map do |meal| %>
              <li><%= meal.protein.capitalize %></li>
          <% end %>
      </div>
    <% else %>
      <h4> No favorites yet! </h4>
    <% end %>

    <div class="col-md-8 well">
      <h4><%= link_to "My Meal Plan", meal_plan_path(mealplan) %></h4>
      <ul>
        <li><%= pluralize(mealplan.meals.count, "meals") if mealplan.meals %></li>
         <li><%= mealplan.goal %> (goal)</li>
         <li><%= mealplan.description %> (description)</li>
       </ul>
       </p>
         <span class="quiet"></span><small>Created by <%= mealplan.user.try(:name) %></small></span><br>
         <span class="quiet"></span><small>Created <%= time_ago_in_words(mealplan.created_at) %> ago</small></span>
       </p>
       <% if logged_in? && current_user == mealplan.user %>
        <div class="mealplan-actions">
         <%= link_to "Add Meals +", new_meal_plan_meal_schedule_path(mealplan), class:"btn btn-xs btn-xlarge" %>
         <%= link_to "View Meals +", meal_plan_meal_schedules_path(mealplan), class:"btn btn-xs btn-primary" %>
         <%= link_to "Edit Meal Plan", edit_meal_plan_path(mealplan), class:"btn btn-xs btn-warning" %>
         <%= link_to "Delete Meal Plan", meal_plan_path(mealplan), method: :delete, data: { confirm: "Are you sure you want to delete this meal plan and associated meals?"}, class:"btn btn-xs btn-danger" %>
       </div>
       <% end %>
    </div>
  </div>

  <div class="row">
  <div class="pull-left liking">
    <%= link_to like_meal_plan_path(mealplan, like: true), data: {meal_plan_id: mealplan.id}, method: :post do %>
      <i class="glyphicon glyphicon-thumbs-up"></i>
    <% end %> <%= mealplan.thumbs_up_total %> ||
    <%= link_to like_meal_plan_path(mealplan, like: false), method: :post do %>
      <i class="glyphicon glyphicon-thumbs-down"></i>
    <% end %> <%= mealplan.thumbs_down_total %>
  </div>
</div>
<% end %>

app/views/meal_plans/edit.html.erb
<%= render "shared/page_title", title: "Edit Your Meal Plan" %>

<div class="col-md-8 well">
  <%= form_for (@meal_plan)  do |f| %>
  <h4><center>Edit meal plan:</h4></center>

  <div class="center">
    <%= f.label :goal %>
    <%= f.select(:goal, ["Weight Loss", "Tone", "Fat Loss", "Gain Muscle", "Maintain"]) %>
  </div>

  <div class="center">
    <%= f.label :description %>
    <%= f.select(:description, ["Regular", "Vegetarian", "Vegan", "Pescatarian", "Gluten Free", "Keto"]) %>
  </div>
  <br><br>

<div class="center">
  <%= f.submit %>
</div>
<% end %>

app/views/meal_plans/index.html.erb
<%= render "shared/page_title", title: "All Your Meal Plans" %>

<div align="center">
  <%= will_paginate %>
</div>
<%= render 'mealplan', obj: @meal_plans %>
<div align="center">
  <%= will_paginate %>
</div>

app/views/meal_plans/new.html.erb
<%= render "shared/page_title", title: "Add New Meal Plan" %>
<%= render 'form', {mealplan: @meal_plan, meal: @meal}%>

app/views/meal_plans/show.html.erb
<%= render "shared/page_title", title: "Your Meal Plan" %>
<div class="well col-md-8 col-md-offset-2">
  <h4><strong>Meal Plan Description: </strong></h4>
  <hr />
  <ul>
    <li><strong><%= @meal_plan.goal %></strong> (Goal)</li>
    <li><strong><%= @meal_plan.description%></strong> (Description)</li>

    <br><br>
    <div class="row">
      <div class="row col-md-8 col-md-offset-2">
        <%= link_to like_meal_plan_path(@meal_plan, like: true), method: :post do %>
          <button type="button" id="yes" class="btn btn-default btn-sm">
            <span class="glyphicon glyphicon-thumbs-up"></span> Like
          </button>
        <% end %> <%= @meal_plan.thumbs_up_total %> ||
        <%= link_to like_meal_plan_path(@meal_plan, like: false), method: :post do %>
        <button type="button" id="no" class="btn btn-default btn-sm">
          <span class="glyphicon glyphicon-thumbs-down"></span> Dislike
        </button>
        <% end %> <%= @meal_plan.thumbs_down_total %>
      </div>
    </div>

    <div id= "likes"></div>
    <div id="dislikes"></div>
    <br><br>

</ul>
<div class="mealplan-actions">
  <% if logged_in? && current_user == @meal_plan.user %>
    <%= link_to "Add Meals +", new_meal_plan_meal_schedule_path(@meal_plan), class:"btn btn-xs btn-xlarge" %>
    <%= link_to "Edit Meal Plan", edit_meal_plan_path(@meal_plan), class:"btn btn-xs btn-warning" %>
    <%= link_to "Delete Meal Plan", meal_plan_path(@meal_plan), method: :delete, data: { confirm: "Are you sure you want to delete this meal plan and associated meals?"}, class:"btn btn-xs btn-danger" %>
  <% end %>
    <%= link_to "View Meals +", meal_plan_meal_schedules_path(@meal_plan), class:"btn btn-xs btn-primary" %>
</div>