config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'sessions#home'

  get '/signup' => 'users#new'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  get '/auth/facebook/callback' => 'sessions#fbcreate'


  resources :users
  resources :meal_plans
  resources :meals, only: [:edit, :index, :show ]
  resources :meal_schedules

  resources :meal_plans do
    resources :meal_schedules, only: [:new, :index, :create]
  end

  resources :meals do
    resources :meal_schedules, only: [:new, :index, :create]
  end

  resources :meal_plans do
  resources :likes, only: [:create]
  member do
    post 'like'
  end
end
end

app/models/meal.rb
class Meal < ApplicationRecord
  has_many :meal_schedules
  has_many :meal_plans, through: :meal_schedules

  validates :protein, :vegetable, :side, :day, :beverage, :beverage_ounces, presence: true
  validates_inclusion_of:favorite, in: [true, false]

  scope :favorite, -> { where(favorite: true) unless Meal.all.empty? }
  default_scope -> { order(updated_at: :desc)}
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  before_action :set_meal, only: [:show, :edit, :update]

  def index
    if params[:meal_plan_id] && mealplan = MealPlan.find_by_id(params[:meal_plan_id])
      @meals = mealplan.meals.paginate(page: params[:page], per_page: 2)
    else
      @meals = current_user.meals.paginate(page: params[:page], per_page: 2)
    end
  end

  def show
  end

  def edit
  end

  def update
    set_meal
    redirect_if_not_logged_in
  if @meal.update(meal_params)
    flash[:success] = "Your meal was updated!"
    redirect_to meal_path(@meal)
  else
    render :edit
  end
end

private
  def meal_params
    params.require(:meal).permit(:protein, :day, :vegetable, :side, :beverage_ounces, :beverage, :favorite)
  end

  def set_meal
    @meal = Meal.find_by(id: params[:id])
    if !@meal
      flash[:danger] = "Meal not Found!"
      redirect_to meals_path
    end
  end
end

app/views/meals/_form.html.erb
<%= form_for [@meal] do |f| %>

<%= render partial: 'layouts/errors', locals: {object: @meal} %>
  <div class="col-md-8 well">


  <%= f.label :protein %>
  <%= f.text_field :protein, placeholder: "Chicken" %>

  <%= f.label :vegetable %>
  <%= f.text_field :vegetable, placeholder: "Spinach" %>

  <%= f.label :side %>
  <%= f.text_field :side, placeholder: "Fries" %>

  <%= f.label :beverage %>
  <%= f.text_field :beverage, placeholder: "Water" %>

  <%= f.label :beverage_ounces %>
  <%= f.number_field :beverage_ounces, placeholder: "16 ounces" %>

  <%= f.label :day %>
  <%= f.date_field :day %>



  <%= f.label :favorite %>
  <%= f.select :favorite, [['No', 'false'],['Yes', 'true']] %>


<br><br>


  <%= f.label :meal_plan_id, "Select a Meal Plan"%>
  <%= f.collection_select :meal_plan_ids, MealPlan.all, :id, :goal, prompt: true %>


  <br><br>

<div class="center">
  <%= f.submit %>
</div>
<% end %>

app/views/meals/_meal.html.erb
<% obj.each do |meal| %>
  <div class="row">
    <div class="col-md-2">
      <section class ="center">
      </section>
    </div>
    <div class="col-md-8 well">
       <h5><%= link_to "#{meal.protein.capitalize}", meal_path(meal), {class: "myMeal", data: {meal_id: meal.id}} %></h5>
        <ul id="meal-<%= meal.id %>">
          <li> Eaten on: <%= meal.try(:day).strftime("%b %d, %Y") %></li>
          <li>Favorite(T/F)? <%= meal.try(:favorite) %></li>
        </ul>
       <p>
         <span class="quiet"></span><small>Created <%= time_ago_in_words(meal.created_at) %> ago</small></span>
       </p>
       <div class="mealplan-actions">
        <%= link_to "View Meal Schedule", meal_meal_schedules_path(meal), class:"btn btn-xs btn-primary" %>
       </div>

    </div>
  </div>
<% end %>

app/views/meals/edit.html.erb
<%= render "shared/page_title", title: "Edit Your Meals" %>
<%= render partial: 'layouts/errors', locals: {object: @meal} %>

<div class="col-md-8 well">

<%= form_for [@meal]  do |f| %>

  <%= f.label :protein %>
  <%= f.text_field(:protein) %>

  <%= f.label :vegetable %>
  <%= f.text_field(:vegetable) %>

  <%= f.label :side %>
  <%= f.text_field(:side) %>

  <%= f.label :beverage %>
  <%= f.text_field(:beverage) %>

  <%= f.label :beverage_ounces %>
  <%= f.number_field(:beverage_ounces) %>

  <%= f.label :day %>
  <%= f.date_field(:day) %>

  <%= f.label :favorite %>
  <%= f.select :favorite, [['No', 'false'],['Yes', 'true']] %>

  <br><br>

  <%= f.label :meal_plan_id, "Select a Meal Plan"%>
  <%= f.collection_select :meal_plan_ids, MealPlan.all, :id, :goal, prompt: true %>


  <br><br>
  <%= f.submit %>
<% end %>

app/views/meals/index.html.erb
<%= render "shared/page_title", title: "All Your Meals" %>

<div align="center">
  <%= will_paginate %>
</div>
<%= render 'meal', obj: @meals %>
<div align="center">
  <%= will_paginate %>
</div>

app/views/meals/new.html.erb
<%= render "shared/page_title", title: "Add Your Meals" %>

<%= render 'form', {meal: @meal} %>

app/views/meals/show.html.erb
<%= render "shared/page_title", title: "Your Meals" %>

<div class="col-md-8 well">
  <h4> This meal contains: </h4>
<ul>
  <li>Protein: <%= @meal.try(:protein).capitalize %></li>
  <li>Veggies: <%= @meal.try(:vegetable).capitalize %></li>
  <li>Sides: <%= @meal.try(:side).capitalize %></li>
  <li><%= @meal.try(:beverage_ounces) %> ounces of <%= @meal.try(:beverage) %></li>
  <li>Eaten on: <%= @meal.try(:day).strftime("%b %d, %Y")%></li>
  <li>Favorite? <%= @meal.try(:favorite) %></li>
</ul>

<div class="mealplan-actions">
  <%= link_to "View Meal Schedules", meal_meal_schedules_path(@meal), class:"btn btn-xs btn-primary" %>
</div>