config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'sessions#home'

  get '/signup' => 'users#new'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  get '/auth/facebook/callback' => 'sessions#fbcreate'


  resources :users
  resources :meal_plans
  resources :meals, only: [:edit, :index, :show ]
  resources :meal_schedules

  resources :meal_plans do
    resources :meal_schedules, only: [:new, :index, :create]
  end

  resources :meals do
    resources :meal_schedules, only: [:new, :index, :create]
  end

  resources :meal_plans do
  resources :likes, only: [:create]
  member do
    post 'like'
  end
end
end

app/models/meal_schedule.rb
class MealSchedule < ApplicationRecord
  belongs_to :meal
  belongs_to :meal_plan

  validates :eating_time, :meal_type, presence: true
  default_scope -> { order(updated_at: :desc)}

  accepts_nested_attributes_for :meal, reject_if: :all_blank


  def meal=(attributes)
    self.build_meal(attributes) unless self.meal_id
  end
end

app/controllers/meal_schedules_controller.rb
class MealSchedulesController < ApplicationController
  before_action :set_meal_schedules, only: [:edit, :update, :show, :delete]
  before_action :redirect_if_not_logged_in, only: [:new, :create, :edit, :update]
  before_action :require_same_user, only: [:edit, :update, :delete]

  def index
    if params[:meal_id] && meal = Meal.find_by_id(params[:meal_id])
      @meal_schedules = meal.meal_schedules.paginate(page: params[:page], per_page: 2)
    else
      @meal_schedules = current_user.meal_schedules.paginate(page: params[:page], per_page: 2)
    end
  end

  def new
    if current_user && params[:meal_plan_id] && @mealplan = MealPlan.find_by_id(params[:meal_plan_id])
      @meal_schedule = @mealplan.meal_schedules.build
      @meal_schedule.build_meal
    else
      @meal_schedule = MealSchedule.new
      @meal_schedule.build_meal
    end
  end


    def create
      @meal_schedule = MealSchedule.new(meal_schedule_params)
      if @meal_schedule.save
        flash[:success] = "Your meal schedule was created!"
        redirect_to meal_schedule_path(@meal_schedule)
      else
        render :new
      end
    end

  def show
  end

  def edit
  end

  def update
    if @meal_schedule.update(meal_schedule_params)
      flash[:success] = "Your meal schedule was updated!"
      redirect_to meal_schedule_path(@meal_schedule)
    else
      render :edit
    end
  end

  def destroy
    @meal_schedule.destroy
    flash[:success] = "Your meal schedule was deleted!"
    redirect_to meal_schedules_path
  end

  private

    def meal_schedule_params
      params.require(:meal_schedule).permit(:eating_time, :meal_type, :meal_id, :meal_plan_id, meal_attributes: [:protein, :vegetable, :side, :day, :beverage, :favorite, :beverage_ounces])
    end

    def set_meal_schedules
      @meal_schedule = MealSchedule.find_by(id: params[:id])
      if @meal_schedule.nil?
        flash[:danger] = "Meal Schedule not Found!"
        redirect_to meal_schedules_path
      end
    end

    def require_same_user
      set_meal_schedules
      if current_user.id != @meal_schedule.meal_plan.user_id
        flash[:danger] = "You can only edit or delete your own meal schedule"
        redirect_to meal_schedules_path
    end
  end
end

app/views/meal_schedules/_form.html.erb
<%= form_for @meal_schedule, :html => {:class => "meal-form"} do |f| %>
  <%= render partial: 'layouts/errors', locals: {object: @meal_schedule} %>
  <%= f.hidden_field :meal_id %>

  <div class="col-md-8 well">

<div class="center">
  <%= f.label :eating_time %>
  <%= f.select(:eating_time, ["Morning", "Afternoon", "Evening", "Night"]) %>
</div>

<div class="center">
  <%= f.label :meal_type %>
  <%= f.select(:meal_type, ["Breakfast", "Lunch", "Dinner", "Snack", "Dessert"]) %>
</div>

<div class="center">
  <%= f.label :meal_id, "Select a Meal"%>
  <%= f.collection_select :meal_id, Meal.all, :id, :protein, prompt: true %>
</div>

<div class="center">
  <%= f.label :meal_plan_id, "Select a Meal Plan"%>
  <%= f.collection_select :meal_plan_id, MealPlan.all, :id, :goal, prompt: true %>
</protein

  <br><br>

    <% if !params[:meal_id] %>
      <h4>Or add a new meal:</h4>

      <%= f.fields_for :meal do |v|%>
      <%= v.label :protein %>
      <%= v.text_field :protein, placeholder: "Chicken" %>

      <%= v.label :vegetable %>
      <%= v.text_field :vegetable, placeholder: "Spinach" %>

      <%= v.label :side %>
      <%= v.text_field :side, placeholder: "Fries" %>

      <%= v.label :beverage %>
      <%= v.text_field :beverage, placeholder: "Water" %>

      <%= v.label :beverage_ounces %>
      <%= v.number_field :beverage_ounces, placeholder: "16 ounces" %>

      <%= v.label :day %>
      <%= v.date_field :day %>

      <%= v.label :favorite %>
      <%= v.select :favorite, [['No', 'false'],['Yes', 'true']] %>
      <% end %>
    <% end %>

    <br><br>



<div class="center">
  <%= f.submit %>
</div>

<br><br>

<div id="mealResult">
  <h2 id="mealMealType"></h2>
  <p id="mealEatingTime"></p>
  <p id="mealProtein"></p>
  <p id="mealVegetable"></p>
  <p id="mealSide"></p>
  <p id="mealBeverage"></p>
</div>


  <% end %>

app/views/meal_schedules/_mealschedule.html.erb
<% obj.each do |mealschedule| %>
  <div class="row">
    <div class="col-md-2">
      <section class ="center">

      </section>
    </div>
    <div class="col-md-8 well">
      <h5>Meal Details: </h5>
       <ul>
         <li><%= mealschedule.meal.try(:protein).capitalize %></li>
         <li><%= mealschedule.meal.try(:vegetable).capitalize %></li>
         <li><%= mealschedule.meal.try(:side).capitalize %></li>
         <li><%= mealschedule.meal.try(:beverage_ounces) %> ounces of <%= mealschedule.meal.try(:beverage) %></li>
         <li><%= mealschedule.meal.try(:day).strftime("%b %d, %Y") %></li>
         <li>Favorite(T/F)? <%= mealschedule.meal.try(:favorite) %></li>
       </ul>
       <h5><%= link_to "Meal Schedule:", meal_schedule_path(mealschedule) %></h5>
       <ul>
         <li> Eating Time: <%= mealschedule.eating_time %></li>
         <li> Meal Type: <%= mealschedule.meal_type %></li>
       </ul>
       <p>
         <span class="quiet"></span><small>Created <%= time_ago_in_words(mealschedule.created_at) %> ago</small></span>
       </p>
       <% if logged_in? && current_user.id == mealschedule.meal_plan.user_id %>
        <div class="mealplan-actions">
          <%= link_to "Edit Meal Schedule", edit_meal_schedule_path(mealschedule),  class:"btn btn-xs btn-warning" %>
          <%= link_to "Delete Meal Schedule", meal_schedule_path(mealschedule), method: :delete, data: { confirm: "Are you sure you want to delete this meal schedule?"}, class:"btn btn-xs btn-danger" %>
        </div>
        <% end %>
    </div>
  </div>
<% end %>

app/views/meal_schedules/edit.html.erb
<%= render "shared/page_title", title: "Edit Meal Schedule" %>
<%= render 'form', {meal_schedule: @meal_schedule} %>

app/views/meal_schedules/index.html.erb
<%= render "shared/page_title", title: "All Your Meal Schedules" %>

<div align="center">
  <%= will_paginate %>
</div>
<%= render 'mealschedule', obj: @meal_schedules %>
<div align="center">
  <%= will_paginate %>
</div>

app/views/meal_schedules/new.html.erb
<%= render "shared/page_title", title: "Add Meal Schedule" %>

<%= render 'form', {meal_schedule: @meal_schedule} %>

app/views/meal_schedules/show.html.erb
<%= render "shared/page_title", title: "Current Meal Schedule" %>

<div class="col-md-8 well">
<p> Today you ate: </p>
  <ul>
    <li><%= @meal_schedule.meal.try(:protein).capitalize %></li>
    <li><%= @meal_schedule.meal.try(:vegetable).capitalize %></li>
    <li><%= @meal_schedule.meal.try(:side).capitalize %></li>
    <li><%= @meal_schedule.meal.try(:beverage_ounces) %> ounces of <%= @meal_schedule.meal.try(:beverage) %></li>
    <li><%= @meal_schedule.meal.try(:day).strftime("%b %d, %Y") %></li>
    <li>Favorite(T/F)? <%= @meal_schedule.meal.try(:favorite) %></li>
  </ul>
  </ul>
<p> Meal Details: </p>
  <ul>
    <li><strong><%= @meal_schedule.eating_time %></strong> (eating time)</li>
    <li><strong><%= @meal_schedule.meal_type %></strong> (type)</li>
  </ul>


<div class="mealplan-actions">
  <% if logged_in? && current_user == @meal_schedule.meal_plan.user %>
    <%= link_to "Edit Meal Schedule", edit_meal_schedule_path(@meal_schedule),  class:"btn btn-xs btn-warning" %>
    <%= link_to "Delete Meal Schedule", meal_schedule_path(@meal_schedule), method: :delete, data: { confirm: "Are you sure you want to delete this meal schedule?"}, class:"btn btn-xs btn-danger" %>
  <% end %>
  <%= link_to "See Meal Schedules", meal_schedules_path(@meal_schedule), class:"btn btn-xs btn-xlarge" %>
</div>