config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'sessions#home'

  get '/signup' => 'users#new'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  get '/auth/facebook/callback' => 'sessions#fbcreate'


  resources :users
  resources :meal_plans
  resources :meals, only: [:edit, :index, :show ]
  resources :meal_schedules

  resources :meal_plans do
    resources :meal_schedules, only: [:new, :index, :create]
  end

  resources :meals do
    resources :meal_schedules, only: [:new, :index, :create]
  end

  resources :meal_plans do
  resources :likes, only: [:create]
  member do
    post 'like'
  end
end
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h2 class="panel-title">
            <%= pluralize(object.errors.count, "error") %>
            prohibited this <%= object.class %> from being saved:
          </h2>
          <div class="panel-body">
            <ul>
              <% object.errors.full_messages.each do |error_message| %>
                <li> <%= error_message %> </li>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <strong><a href="https://github.com/WhitnyNicole/meal_plan_tracker"> Created by Whitny</a></strong>

  </small>
</footer>

app/views/layouts/_messages.html.erb
<!-- <% if flash[:success] %>
  <h3 style="color: green;"><%= flash[:success] %></h3>
<% end %>

<% if flash[:error] %>
  <h3 style="color: red;"><%= flash[:error] %></h3>
<% end %> -->


<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <% flash.each do |name, msg| %>
      <div class="alert alert-<%= name %>">
        <a href="#" class="close" data-dismiss="alert">&#215;</a>
        <%= msg %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle Navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "My Meal Tracker", root_path, class: "navbar-brand", id:"logo" %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if logged_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">See Details <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Your Meal Plans",meal_plans_path %>
            <li><%= link_to "Your Meals",meals_path %></li>
            <li><%= link_to "All Meal Schedules",meal_schedules_path %></li>
          </ul>
        </li>
        <% end %>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
          <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %>'s Profile <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Your Profile", user_path(current_user) %></li>
            <li><%= link_to "Create Meal Plan", new_meal_plan_path%></li>
            <li><%= link_to "Log Out", logout_path, method: :delete %></li>
          </ul>
        </li>
        <% else %>
          <li><%= link_to "Log In", login_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MealPlanTracker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <div class="container">
    <%= yield %>
  </div>
    <%= render 'layouts/footer' %>
  </body>
</html>